:sectnums!:
:hardbreaks:
:scrollbar:
:data-uri:
:toc2:
:showdetailed:
:imagesdir: ./images


= Using Red Hat OpenStack Platform Director to Provision Red Hat OpenShift on Bare Metal

== Configure Bare Metal Node for Red Hat OpenShift

=== Add DNS Record for the Bare Metal Node

Red Hat OpenShift requires the nodes to be registered to DNS to function correctly. This lab provides a simple playbook to add the bare metal node to the `openshift-dns` DNS server.

. Update the `update-dns.yaml` file under the `/home/stack/` directory on the undercloud node, uncommenting and editing the following line using the IP address of the bare metal node obtained in the previous lab:
+
.Before the change
[source,yaml]
----
         #- {server: "ocp-node02", ip: "192.0.3.12"}
----
+
.After the change
[source,yaml]
----
       - {server: "ocp-node02", ip: "<insert the IP address here>"}
----
+
[IMPORTANT]
Please verify the list indentation in the YAML file while updating the entry in the playbook.

. Run the the `update-dns.yaml` playbook:
+
[%nowrap]
----
(overcloud) [stack@undercloud ~]$ ansible-playbook update-dns.yaml
----
+
.Sample output
[%nowrap]
----
PLAY [Update wildcard DNS to the floating Ip] ************************************************************************************************************************************************

TASK [Modify wildcard DNS] *******************************************************************************************************************************************************************
ok: [localhost]

TASK [Modify console DNS] ********************************************************************************************************************************************************************
ok: [localhost]

TASK [Modify servers DNS] ********************************************************************************************************************************************************************
ok: [localhost] => (item={u'ip': u'192.0.3.12', u'server': u'ocp-node01'})
ok: [localhost] => (item={u'ip': u'192.0.3.22', u'server': u'ocp-infra01'})
ok: [localhost] => (item={u'ip': u'192.0.3.16', u'server': u'ocp-master01'})
changed: [localhost] => (item={u'ip': u'192.0.3.14', u'server': u'ocp-node02'})

PLAY RECAP ***********************************************************************************************************************************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0
----


=== Configure Docker Daemon

The following tasks can be performed using the `cloud-init` user data during the server provisioning. However, in this lab, this is a manual task to demonstrate the required steps.

. Connect to the bare metal node:
+
[%nowrap]
----
(overcloud) [stack@undercloud ~]$ ssh cloud-user@$(openstack server show  -f value -c addresses ocp-node02 | cut -d = -f 2)
[cloud-user@ocp-node02 ~]$ sudo -i
----

. Fix the DNS server IP address in the `/etc/resolv.conf` file on the bare metal node:
+
[%nowrap]
----
[root@ocp-node02 ~]# sed -i '/nameserver 192.168.122.1/d' /etc/resolv.conf
----
+
[IMPORTANT]
There is a bug in the qcow2 image used (Bugzilla [https://bugzilla.redhat.com/show_bug.cgi?id=1545842]
). The `/etc/resolv.conf` file includes 192.168.122.1 as the DNS server.

. Configure repositories to install the `docker` and `openshift` packages.

.. Create a file named `open.repo` inside `/etc/yum.repos.d/` directory:
+
[%nowrap]
----
[root@ocp-node02 ~]# cat <<EOF >/etc/yum.repos.d/open.repo
[rhel-7-server-rpms]
name=Red Hat Enterprise Linux 7 Server (RPMs)
baseurl=http://192.0.2.253/repos/rhel-7-server-rpms
enabled=1
gpgcheck=0

[rhel-7-server-extras-rpms]
name=Red Hat Enterprise Linux 7 Server - Extras (RPMs)
baseurl=http://192.0.2.253/repos/rhel-7-server-extras-rpms
enabled=1
gpgcheck=0

[rhel-7-server-rh-common-rpms]
name=Red Hat Enterprise Linux 7 Server - RH Common (RPMs)
baseurl=http://192.0.2.253/repos/rhel-7-server-rh-common-rpms
enabled=1
gpgcheck=0

[rhel-ha-for-rhel-7-server-rpms]
name=Red Hat Enterprise Linux High Availability (for RHEL 7 Server) (RPMs)
baseurl=http://192.0.2.253/repos/rhel-ha-for-rhel-7-server-rpms
enabled=1
gpgcheck=0

[rhel-7-server-ansible-2.4-rpms]
name=Ansible 2.4
baseurl=http://192.0.2.253/repos/rhel-7-server-ansible-2.4-rpms
enabled=1
gpgcheck=0
[rhel-7-server-ose-3.10-rpms]
name=Red Hat OpenShift 3.10 (RPMs)
baseurl=http://192.0.2.253/repos/rhel-7-server-ose-3.10-rpms
enabled=1
gpgcheck=0
EOF
----

.. Ensure the repositories are reachable:
+
[%nowrap]
----
[root@ocp-node02 ~]# yum repolist
----
+
.Expected output
[%nowrap]
----
Loaded plugins: search-disabled-repos
repo id                                                 repo name                                                                                       status
rhel-7-server-ansible-2.4-rpms                          Ansible 2.4                                                                                        10
rhel-7-server-extras-rpms                               Red Hat Enterprise Linux 7 Server - Extras (RPMs)                                                 105
rhel-7-server-ose-3.10-rpms                             Red Hat OpenShift 3.10 (RPMs)                                                                     520
rhel-7-server-rh-common-rpms                            Red Hat Enterprise Linux 7 Server - RH Common (RPMs)                                               84
rhel-7-server-rpms                                      Red Hat Enterprise Linux 7 Server (RPMs)                                                        5,285
rhel-ha-for-rhel-7-server-rpms                          Red Hat Enterprise Linux High Availability (for RHEL 7 Server) (RPMs)                              55
repolist: 6,059

----

. Install the `docker` package:
+
[%nowrap]
----
[root@ocp-node02 ~]# yum install -y docker
----
+
.Expected output
[%nowrap]
----
<<OUTPUT TRUNCATED>>
Installed:
  docker.x86_64 2:1.13.1-68.gitdded712.el7

Dependency Installed:
  atomic-registries.x86_64 1:1.22.1-22.git5a342e3.el7         container-selinux.noarch 2:2.66-1.el7                          container-storage-setup.noarch 0:0.10.0-1.gitdf0dcd5.el7
  device-mapper-event.x86_64 7:1.02.146-4.el7                 device-mapper-event-libs.x86_64 7:1.02.146-4.el7               device-mapper-persistent-data.x86_64 0:0.7.3-3.el7
  docker-client.x86_64 2:1.13.1-68.gitdded712.el7             docker-common.x86_64 2:1.13.1-68.gitdded712.el7                docker-rhel-push-plugin.x86_64 2:1.13.1-68.gitdded712.el7
  libaio.x86_64 0:0.3.109-13.el7                              lvm2.x86_64 7:2.02.177-4.el7                                   lvm2-libs.x86_64 7:2.02.177-4.el7
  oci-register-machine.x86_64 1:0-6.git2b44233.el7            oci-systemd-hook.x86_64 1:0.1.16-1.git05bd9a0.el7              oci-umount.x86_64 2:2.3.3-3.gite3c9055.el7
  python-pytoml.noarch 0:0.1.14-1.git7dea353.el7              skopeo-containers.x86_64 1:0.1.31-1.dev.gitae64ff7.el7         yajl.x86_64 0:2.0.4-4.el7

Complete!
----

. Generate the `/etc/sysconfig/docker-storage-setup` configuration:
+
[%nowrap]
----
[root@ocp-node02 ~]# cat <<EOF >/etc/sysconfig/docker-storage-setup
VG=docker-vg
DEVS=/dev/vdb
EOF
----
+
The system has a second disk (`/dev/vdb`) to be used for Docker storage.

. Run `docker-storage-setup` to configure the storage:
+
[%nowrap]
----
[root@ocp-node02 ~]# docker-storage-setup
----
+
.Expected output
[%nowrap]
----
INFO: Volume group backing root filesystem could not be determined
INFO: Writing zeros to first 4MB of device /dev/vdb
4+0 records in
4+0 records out
4194304 bytes (4.2 MB) copied, 0.0081824 s, 513 MB/s
INFO: Device node /dev/vdb1 exists.
  Physical volume "/dev/vdb1" successfully created.
  Volume group "docker-vg" successfully created
  Rounding up size to full physical extent 32.00 MiB
  Thin pool volume with chunk size 512.00 KiB can address at most 126.50 TiB of data.
  Logical volume "docker-pool" created.
  Logical volume docker-vg/docker-pool changed.
----

. Start the Docker daemon:
+
[%nowrap]
----
[root@ocp-node02 ~]# systemctl enable docker && systemctl start docker
----

. Ensure the correct storage is configured:
+
[%nowrap]
----
[root@ocp-node02 ~]# docker info 2>/dev/null| head
----
+
.Expected output
[%nowrap]
----
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.1
Storage Driver: devicemapper
 Pool Name: docker--vg-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
----
+
[NOTE]
Notice the `Storage Driver` and `Pool Name`.

. Exit from the `ocp-node02` instance:
+
[%nowrap]
----
[root@ocp-node02 ~]# exit
----
