:sectnums!:
:hardbreaks:
:scrollbar:
:data-uri:
:toc2:
:showdetailed:
:imagesdir: ./images


= Red Hat Tech Exchange 2018 - Using OpenStack director to provision OpenShift on bare metal

== Review current nodes in OpenShift.

. Connect to `bastion` node
+
[%nowrap]
----
(overcloud) [stack@undercloud ~]$ ssh cloud-user@192.0.3.18
----
+
[%nowrap]
----
[cloud-user@ocp-bastion ~]$ sudo -i
----
. Get the list of the current nodes of OpenShift
+
[%nowrap]
----
[cloud-user@ocp-master01 ~]$ oc get nodes
----
+
.Expected output
[%nowrap]
----
NAME           STATUS    ROLES     AGE       VERSION
ocp-infra01    Ready     infra     1d        v1.10.0+b81c8f8
ocp-master01   Ready     master    1d        v1.10.0+b81c8f8
ocp-node01     Ready     compute   1d        v1.10.0+b81c8f8
----

. Edit the inventory file `./hosts` to include the new node
+
.Add a new section named _new_nodes_ after _nodes_ section.
[NOTE]
+
The [new_nodes] `child group` is alread available in the provided hosts file. You may uncomment the line and update the `ip address` of the `ocp-node02` server. Also check the `OpenShift Node Group` configuration in the `hosts` file. We created a custom `node group` for the `baremetal` cluster nodes with `type=bm` label. This label could be used in the `Node Selector` spectification for the Application Pods.
+
[%nowrap]
----
[new_nodes]
ocp-node02.openshift.example.com openshift_ip=<ocp-node02-ip> ansible_host=<ocp-node02-ip> openshift_node_group_name='node-config-bm-compute'
----
+
.OpenShift Node Group Reference
NOTE: The entry is for reference only and is avialbale in the custom `hosts` file provided.
+
[%nowrap]
----
openshift_node_groups=[{'name': 'node-config-master', 'labels': ['node-role.kubernetes.io/master=true']}, {'name': 'node-config-infra', 'labels': ['node-role.kubernetes.io/infra=true', 'env=infra']}, {'name': 'node-config-compute', 'labels': ['node-role.kubernetes.io/compute=true', 'type=vm',  'env=app'], 'edits': [{ 'key': 'kubeletArguments.pods-per-core','value': ['20']}]},{'name': 'node-config-bm-compute', 'labels': ['node-role.kubernetes.io/compute=true', 'type=bm'], 'edits': [{ 'key': 'kubeletArguments.pods-per-core','value': ['20']}]}]
----
+
[%nowrap]
----
[new_nodes]
ocp-node02.openshift.example.com openshift_ip=192.0.3.14 ansible_host=192.0.3.14 openshift_node_group_name='node-config-compute'
----
+
.Note the  _new_nodes_ inside _OSEv3:children_ section
[%nowrap]
----
[OSEv3:children]
masters
nodes
new_nodes
----

. Run `prerequisites.yaml` playbook to configure the prerequisites for the new node.
+
[%nowrap]
----
[root@ocp-bastion ~]# ansible-playbook -i hosts  /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml
----
[NOTE]
Type "yes" when it ask to continue connecting to the new node.
+
.Expected output
[%nowrap]
----
<<TRUNCATED OUTPUT>>
PLAY RECAP ***********************************************************************************************************************************************************************************
localhost                  : ok=12   changed=0    unreachable=0    failed=0
ocp-infra01.openshift.example.com : ok=31   changed=5    unreachable=0    failed=0
ocp-master01.openshift.example.com : ok=70   changed=7    unreachable=0    failed=0
ocp-node01.openshift.example.com : ok=31   changed=5    unreachable=0    failed=0
ocp-node02.openshift.example.com : ok=65   changed=19   unreachable=0    failed=0


INSTALLER STATUS *****************************************************************************************************************************************************************************
Initialization  : Complete (0:02:49)
----

. Run `scaleup.yaml` playbook to install and configure OpenShift on the node
+
[%nowrap]
----
[root@ocp-bastion ~]# ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/openshift-node/scaleup.yml
----
+
.Expected output
[%nowrap]
----
<<TRUNCATED OUTPUT>>
PLAY RECAP ***********************************************************************************************************************************************************************************
localhost                  : ok=25   changed=0    unreachable=0    failed=0
ocp-master01.openshift.example.com : ok=67   changed=1    unreachable=0    failed=0
ocp-node02.openshift.example.com : ok=162  changed=59   unreachable=0    failed=0


INSTALLER STATUS *****************************************************************************************************************************************************************************
Initialization              : Complete (0:00:54)
Node Bootstrap Preparation  : Complete (0:03:13)
Node Join                   : Complete (0:03:53)
----

. Check the  nodes to ensure new node appears
+
[%nowrap]
----
oc get nodes --show-labels
----
+
.Sample output
[%nowrap]
----
NAME           STATUS    ROLES     AGE       VERSION           LABELS
ocp-infra01    Ready     infra     4d        v1.10.0+b81c8f8   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=763b980f-c9d2-40ac-8c5c-cc18be29a83a,beta.kubernetes.io/os=linux,env=infra,failure-domain.beta.kubernetes.io/region=regionOne,failure-domain.beta.kubernetes.io/zone=nova,kubernetes.io/hostname=ocp-infra01,node-role.kubernetes.io/infra=true
ocp-master01   Ready     master    4d        v1.10.0+b81c8f8   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=763b980f-c9d2-40ac-8c5c-cc18be29a83a,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=regionOne,failure-domain.beta.kubernetes.io/zone=nova,kubernetes.io/hostname=ocp-master01,node-role.kubernetes.io/master=true
ocp-node01     Ready     compute   4d        v1.10.0+b81c8f8   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=763b980f-c9d2-40ac-8c5c-cc18be29a83a,beta.kubernetes.io/os=linux,env=app,failure-domain.beta.kubernetes.io/region=regionOne,failure-domain.beta.kubernetes.io/zone=nova,kubernetes.io/hostname=ocp-node01,node-role.kubernetes.io/compute=true,type=vm
----
. Check the  nodes to ensure new node appears
+
[%nowrap]
----
oc get nodes --show-labels
----

. Check the nodes with the label `type=vm`
+
[%nowrap]
----
oc get nodes -l type=vm
----
+
.Sample Output
[%nowrap]
----
NAME         STATUS    ROLES     AGE       VERSION
ocp-node01   Ready     compute   4d        v1.10.0+b81c8f8
----
. Check the  nodes with the lable `type=bm`
+
[%nowrap]
----
oc get nodes -l type=bm
----
+
.Sample Output
+
[%nowrap]
----
NAME         STATUS    ROLES     AGE       VERSION
ocp-node02   Ready     compute   4d        v1.10.0+b81c8f8
----
