:sectnums!:
:hardbreaks:
:scrollbar:
:data-uri:
:toc2:
:showdetailed:
:imagesdir: ./images


= Using Red Hat OpenStack Platform Director to Provision Red Hat OpenShift on Bare Metal

== Deploying Application in Hybrid Cluster

Assume a scenario where you required a multi-tier application, in which each of the tiers needs a particular type of compute node due to its resource utilization and security patterns.

In this lab, we have the `Deployment Configuration` manifest for a two-tier application (WordPress). The customer wishes to deploy the pods of the front tier (PHP) to flexible and horizontally-scalable virtual compute nodes, and the database (MySQL) tier pods to a high-capacity bare-metal compute node.

We have the deployment manifest for both tiers available in the `/root` directory on the bastion node.

. Verify the `nodeSelector` specification in both Deployment Configuration (dc) manifests:
+
[%nowrap]
----
[root@ocp-bastion ~]# vi frontend-app.yaml
----

. Search for the `nodeSelector` specification of the front tier manifest:
+
[%nowrap]
----
...
        nodeSelector:
          type: "vm"
...
----

. View the `nodeSelector` in the database tier manifest:
+
[%nowrap]
----
[root@ocp-bastion ~]# vi mysql.yaml
----

. Search for the `nodeSelector` specification of the database tier manifest:
+
[%nowrap]
----
...
        nodeSelector:
          type: "bm"
...
----

. Create a project for the application:
+
[%nowrap]
----
[root@ocp-bastion ~]# oc new-project node-selector-demo
----

. Since the WordPress containers are running with `root` privilege, we need to add an additional security privilege to the `default` service account of the project:
+
[%nowrap]
----
[root@ocp-bastion ~]# oc adm policy add-scc-to-user anyuid -z default -n node-selector-demo
----

. Create the front tier Deployment Configuration using the `frontend-app.yaml` manifest:
+
[%nowrap]
----
[root@ocp-bastion ~]# oc create -f frontend-app.yaml
----
+
.Expected output
+
[%nowrap]
----
imagestream.image.openshift.io "wordpress" created
deploymentconfig.apps.openshift.io "wordpress" created
service "wordpress" created
----

. Create the database tier Deployment Configuration using the `mysql.yaml` manifest:
+
[%nowrap]
----
[root@ocp-bastion ~]# oc create -f  mysql.yaml
----
+
.Expected output
+
[%nowrap]
----
imagestream.image.openshift.io "db" created
deploymentconfig.apps.openshift.io "db" created
----

. Verify the pod creation of the respective tiers in the selected nodes as per the `nodeSelector` specification:
+
[%nowrap]
----
[root@ocp-bastion ~]# oc get po -o wide  -n node-selector-demo -w
----
+
.Expected output
[%nowrap]
----
NAME                READY     STATUS    RESTARTS   AGE       IP           NODE
db-1-jlm6x          1/1       Running   0          2m        10.131.0.3   ocp-node02
wordpress-1-x2snc   1/1       Running   0          2m        10.129.0.3   ocp-node01
----
+
You may note that as per the application requirements, the front tier pods deployed on the virtual instance `ocp-node01` and the database tier pods deployed on the bare metal node `ocp-node02`.
