:hardbreaks:
:scrollbar:
:data-uri:
:toc2:
:showdetailed:


== Provision the Lab Environment

=== Set Up SSH

To access the lab environment SSH into the bastion host known as  `Workstation VM`. `workstation` is allowed access from the Internet using SSH authenticated with the student's OPENTLC SSO username and  SSH key.

Before connecting to the lab configure a public SSH key, and upload it at  https://www.opentlc.com/update.  The portal can be accessed using 'OPEN TLC' credentials.

[NOTE]
Did you forget your username or password? Go to `https://www.opentlc.com/pwm` to obtain a username reminder or reset your password.

=== Provision the Lab Environment

Log into the OpenTLC CFME provisioning portal located at `https://labs.opentlc.com/` using the assigned username and password.

Navigate to Services → Catalogs → All Services → RHTE2018 Labs.

On the left, click `OpenShift on Hybrid Openstack` Lab catalog.



On the right, click Order.

Check the box to confirm that you have read and understood the message about the runtime and how to extend it.

On the bottom right, click Submit.


[WARNING]
Do not select App Control → Start after ordering the lab. The build has already started. Selecting Start may corrupt the lab environment or cause other complications.
Wait about 30 minutes for your environment to finish building.

(Optional) Select Status to receive an email message with the status of your environment. You may repeat this step as needed.

[IMPORTANT]
Due to the shared infrastructure of the lab, you may experience a higher response time and latency. It may affect the status of the openstack services too after a 'vm reboot'.To maintain the consistecy of the lab environment , it is adviced to complete all the lab modules in a 'single session'.

After a few minutes, you will receive an email message with instructions and URIs to connect to the lab environment.

=== Connect to the Lab environment

Connect to the Lab Environment using the following command:
----
ssh -i <Your Private Key>  <OPEN-TLC-username>@<workstation URI mentioned in the mail>
                                                                                       
