:hardbreaks:
:scrollbar:
:data-uri:
:toc2:
:showdetailed:

== Set the OpenStack Credentials in the Environment

Set up the shell to access Identity as the administrative user:
----
$ source ~/overcloudrc
----
== Verify the Services

Check that the nova-compute service is running on the controller nodes:
----
openstack compute service list -c Binary -c Host -c Status
----
Make sure the required drivers are enabled:
----
openstack baremetal driver list
----
Ensure that the ironic endpoints are listed:
----
openstack catalog list
----
== Create the Baremetal Flavor

Create the Required Flavor for the Baremetal Servers:
----
openstack flavor create  --id auto --ram 8192 --vcpus 2 --disk 40 --property baremetal=true --public ocp-bm
----
== Upload the Baremetal Images

Upload the  Deployment `kernel` and `ramdisk` to Glance:
----
openstack image create --container-format aki --disk-format aki --public --file /home/stack/images/ironic-python-agent.kernel bm-deploy-kernel
----
----
openstack image create --container-format ari --disk-format ari   --public --file /home/stack/images/ironic-python-agent.initramfs bm-deploy-ramdisk
----

Upload the Ironic Node `image,kernel and ramdisk`:

----
./bm-image-upload.sh
----
NOTE: For the conveninece of the Lab provisioning, required OpenStack  commands are included in the script. You may refer the commands
using the file viewer:
----
view ./bm-image-upload.sh

----

== Create the Host Aggregates

Create a `aggregate` for baremetal nodes called `baremetal-hosts`:
----
openstack aggregate create --property baremetal=true baremetal-hosts
----
Create a `aggregate ` for virtual hosts called `virtual-hosts`:
----
openstack aggregate create --property baremetal=false virtual-hosts
----
Add each `controller` nodes to the baremetal-hosts aggregate:
----
openstack aggregate add host baremetal-hosts overcloud-controller-0.example.com
----
Add each `compute` nodes to the virtual-hosts aggregate:
----
openstack aggregate add host virtual-hosts overcloud-compute-0.example.com
----
----
openstack aggregate add host virtual-hosts overcloud-compute-1.example.com
----
----
openstack aggregate add host virtual-hosts overcloud-compute-2.example.com
----
openstack aggregate add host virtual-hosts overcloud-compute-3.example.com
----
Define the  flavor for `baremetal` nodes:
----
openstack flavor set ocp-bm --property baremetal=true
----
Specify the flavors for `virtual` instanaces:
----
openstack flavor set m1.master --property baremetal=false
----
openstack flavor set m1.node --property baremetal=false
----
== Enroll the Baremetal Nodes

Enroll the baremetal nodes to the `ironic` service:
----
openstack baremetal create bm-enroll.yaml
----
Execute the following tasks on the `enrolled` nodes

*** Assign the `deployment kernel` and `deployment ramdisk`
*** Change the status of the nodes to `manage`
*** `CLEAN the node disks
*** Change the status of the nodes to `available`.
----
./bm-enroll.sh
----
NOTE: The aforementioned tasks are executed using the scripts `bm-enroll.sh`.You may verify the `bm-enroll.yaml` and `bm-enroll.sh` scripts.

Verify the `baremetal` nodes:
----
openstack baremetal node list
----
== Create the Baremetal Servers

Create the `baremetal servers ` using the ansible palybook provided:
----
ansible-playbook -f 10 setupbm.yaml -e domain_name=example.com
----
verify the `baremetal servers`:
----
openstack baremetal server list
----
== Add the Baremetal Servers to the OpenShift Cluster

Add the newly provisioned `baremetal nodes` to the `pre-provisioned` OpenShift cluster:
NOTE: Required `hosts` files are provided in the lab environment. You may verify the `child group` `[new_nodes]`. The `baremetal servers` are assigmed with the label`type=bm-compute` . You may use the label while selecting the nodes for the PoD `deployment`.
----
ansible-playbook -f 10 /usr/share/ansible/openshift-ansible/playbooks/openshift-node/scaleup.yml
----
Post completion of the `scale up`  task, verify the available nodes:
----
oc get nodes  --show-labels
----
== Deploy the Test Application

Create a Project on OpenShift to deploy the `testapp`:
----
oc new-project node-selector-app
----

Deploy the test apps on OpenShift manifests with `NodeSelector`.
----
oc create -f frontend.yaml
----
----
oc create -f db.yaml
----

Verify the `PoD` distribution of the newly deployed application:
----
oc get po -n node-selector-ap -o wide
----
NOTE: You could see that the `email service pods` deployed on `virtual instances` and `mysql` pods on `baremetal servers`.









                                                                                       
